
WIDTH = 800
HEIGHT = 600
UI_HEIGHT = 80
FPS = 30

DEFAULT_PREDATOR_SPEED = 4
DEFAULT_PREY_SPEED = 3

DEFAULT_PREDATOR_REPRO_THRESHOLD = 40
DEFAULT_PREY_REPRO_THRESHOLD = 40

SEEK_RADIUS = 200
FEAR_RADIUS = 150

PREDATOR_ENERGY_LOSS = 0.3
PREY_ENERGY_LOSS = 0.1

PREDATOR_EAT_GAIN = 30
PREY_GRAZE_GAIN = 0.2

MAX_PREY = 120