# Screen settings

WIDTH = 1200
HEIGHT = 600
UI_HEIGHT = 120
FPS = 30

DEFAULT_PREDATOR_SPEED = 4
DEFAULT_PREY_SPEED = 3

DEFAULT_PREDATOR_REPRO_THRESHOLD = 40
DEFAULT_PREY_REPRO_THRESHOLD = 40

SEEK_RADIUS = 200
FEAR_RADIUS = 150

DEFAULT_PREDATOR_ENERGY_LOSS = 0.12
DEFAULT_PREY_ENERGY_LOSS = 0.08

DEFAULT_PREDATOR_EAT_GAIN = 45
DEFAULT_PREY_GRAZE_GAIN = 0.25

MAX_PREY = 200
